name: theme_extensions_gen
description: > 
  Generate Flutter ThemeExtensions from annotated templates with context accessors and no boilerplate.
version: 1.0.1
homepage: https://github.com/kalaganov/theme_extensions_gen
repository: https://github.com/kalaganov/theme_extensions_gen
issue_tracker: https://github.com/kalaganov/theme_extensions_gen/issues
topics:
  - theme-extensions-generator
  - theme-extensions-builder
  - theme-extensions
  - theme-extension
  - theme

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  analyzer: ">=8.0.0 <10.0.0" # https://pub.dev/packages/analyzer
  build: ^4.0.4 # https://pub.dev/packages/build
  source_gen: ^4.1.2 # https://pub.dev/packages/source_gen
  glob: ^2.1.3 # https://pub.dev/packages/glob
  meta: ^1.16.0 # https://pub.dev/packages/meta
  very_good_analysis: ^10.0.0 # https://pub.dev/packages/very_good_analysis
  collection: ^1.18.1
  yaml: ^3.1.3 # https://pub.dev/packages/yaml
  dart_style: ^3.1.3 # https://pub.dev/packages/dart_style
  pub_semver: ^2.2.0 # https://pub.dev/packages/pub_semver

  theme_extensions_gen_annotations: ^0.2.0

dev_dependencies:
  build_runner: ^2.10.5 # https://pub.dev/packages/build_runner
  build_test: ^3.5.5 # https://pub.dev/packages/build_test
  test: ^1.29.0 # https://pub.dev/packages/test
  coverage: ^1.15.0 # https://pub.dev/packages/coverage

  flutter:
    sdk: flutter
