name: theme_extensions_gen
description: > 
  Generate Flutter ThemeExtensions from annotated templates with context accessors and no boilerplate.
version: 0.1.6
homepage: https://github.com/kalaganov/theme_extensions_gen
repository: https://github.com/kalaganov/theme_extensions_gen/tree/main/packages/theme_extensions_gen
issue_tracker: https://github.com/kalaganov/theme_extensions_gen/issues
topics:
  - theme-extensions-generator
  - theme-extensions-builder
  - theme-extensions
  - theme-extension
  - theme

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ">=6.9.0 <8.0.0"
  build: ^2.3.1
  source_gen: ^2.0.0
  glob: ^2.1.3
  meta: ^1.16.0
  very_good_analysis: ^7.0.0
  collection: ^1.18.1
  yaml: ^3.1.3
  dart_style: ^3.0.1
  pub_semver: ^2.2.0

  theme_extensions_gen_annotations: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.2.3
  test: ^1.21.0
  coverage: ^1.13.1

  flutter:
    sdk: flutter
